@host = http://localhost:8000
@agentId = agent-56efc20b-4b7d-418c-be0c-001822223d39

### List all secrets
GET {{host}}/api/secrets?userId={{agentId}}
Content-Type: application/json
Accept: application/json

### Create a new secret
POST {{host}}/api/secrets
Content-Type: application/json
Accept: application/json

{
  "userId": "{{agentId}}",
  "key": "TELEGRAM_BOT_TOKEN",
  "value": "1234567890"
}

### Delete secret
DELETE {{host}}/api/secrets
Content-Type: application/json
Accept: application/json

{
  "userId": "{{agentId}}",
  "key": "TELEGRAM_BOT_TOKEN"
}

### Resolve a secret
POST {{host}}/api/secrets/resolve
Content-Type: application/json
Accept: application/json

{
  "userId": "{{agentId}}",
  "key": "TELEGRAM_BOT_TOKEN"
}